using System;
using System.Collections.Generic;
using System.Linq;
using ExCSS.New.Values;

namespace ExCSS
{
    public static class Colors
    {
        private static readonly Dictionary<string, ColorValue> NamedColors =
            new (StringComparer.OrdinalIgnoreCase)
            {
                {"aliceblue", new ColorValue(TokenValue.Empty, 240, 248, 255)},
                {"antiquewhite", new ColorValue(TokenValue.Empty, 250, 235, 215)},
                {"aqua", new ColorValue(TokenValue.Empty, 0, 255, 255)},
                {"aquamarine", new ColorValue(TokenValue.Empty, 127, 255, 212)},
                {"azure", new ColorValue(TokenValue.Empty, 240, 255, 255)},
                {"beige", new ColorValue(TokenValue.Empty, 245, 245, 220)},
                {"bisque", new ColorValue(TokenValue.Empty, 255, 228, 196)},
                {"black", new ColorValue(TokenValue.Empty, 0, 0, 0)},
                {"blanchedalmond", new ColorValue(TokenValue.Empty, 255, 235, 205)},
                {"blue", new ColorValue(TokenValue.Empty, 0, 0, 255)},
                {"blueviolet", new ColorValue(TokenValue.Empty, 138, 43, 226)},
                {"brown", new ColorValue(TokenValue.Empty, 165, 42, 42)},
                {"burlywood", new ColorValue(TokenValue.Empty, 222, 184, 135)},
                {"cadetblue", new ColorValue(TokenValue.Empty, 95, 158, 160)},
                {"chartreuse", new ColorValue(TokenValue.Empty, 127, 255, 0)},
                {"chocolate", new ColorValue(TokenValue.Empty, 210, 105, 30)},
                {"coral", new ColorValue(TokenValue.Empty, 255, 127, 80)},
                {"cornflowerblue", new ColorValue(TokenValue.Empty, 100, 149, 237)},
                {"cornsilk", new ColorValue(TokenValue.Empty, 255, 248, 220)},
                {"crimson", new ColorValue(TokenValue.Empty, 220, 20, 60)},
                {"cyan", new ColorValue(TokenValue.Empty, 0, 255, 255)},
                {"darkblue", new ColorValue(TokenValue.Empty, 0, 0, 139)},
                {"darkcyan", new ColorValue(TokenValue.Empty, 0, 139, 139)},
                {"darkgoldenrod", new ColorValue(TokenValue.Empty, 184, 134, 11)},
                {"darkgray", new ColorValue(TokenValue.Empty, 169, 169, 169)},
                {"darkgreen", new ColorValue(TokenValue.Empty, 0, 100, 0)},
                {"darkgrey", new ColorValue(TokenValue.Empty, 169, 169, 169)},
                {"darkkhaki", new ColorValue(TokenValue.Empty, 189, 183, 107)},
                {"darkmagenta", new ColorValue(TokenValue.Empty, 139, 0, 139)},
                {"darkolivegreen", new ColorValue(TokenValue.Empty, 85, 107, 47)},
                {"darkorange", new ColorValue(TokenValue.Empty, 255, 140, 0)},
                {"darkorchid", new ColorValue(TokenValue.Empty, 153, 50, 204)},
                {"darkred", new ColorValue(TokenValue.Empty, 139, 0, 0)},
                {"darksalmon", new ColorValue(TokenValue.Empty, 233, 150, 122)},
                {"darkseagreen", new ColorValue(TokenValue.Empty, 143, 188, 143)},
                {"darkslateblue", new ColorValue(TokenValue.Empty, 72, 61, 139)},
                {"darkslategray", new ColorValue(TokenValue.Empty, 47, 79, 79)},
                {"darkslategrey", new ColorValue(TokenValue.Empty, 47, 79, 79)},
                {"darkturquoise", new ColorValue(TokenValue.Empty, 0, 206, 209)},
                {"darkviolet", new ColorValue(TokenValue.Empty, 148, 0, 211)},
                {"deeppink", new ColorValue(TokenValue.Empty, 255, 20, 147)},
                {"deepskyblue", new ColorValue(TokenValue.Empty, 0, 191, 255)},
                {"dimgray", new ColorValue(TokenValue.Empty, 105, 105, 105)},
                {"dimgrey", new ColorValue(TokenValue.Empty, 105, 105, 105)},
                {"dodgerblue", new ColorValue(TokenValue.Empty, 30, 144, 255)},
                {"firebrick", new ColorValue(TokenValue.Empty, 178, 34, 34)},
                {"floralwhite", new ColorValue(TokenValue.Empty, 255, 250, 240)},
                {"forestgreen", new ColorValue(TokenValue.Empty, 34, 139, 34)},
                {"fuchsia", new ColorValue(TokenValue.Empty, 255, 0, 255)},
                {"gainsboro", new ColorValue(TokenValue.Empty, 220, 220, 220)},
                {"ghostwhite", new ColorValue(TokenValue.Empty, 248, 248, 255)},
                {"gold", new ColorValue(TokenValue.Empty, 255, 215, 0)},
                {"goldenrod", new ColorValue(TokenValue.Empty, 218, 165, 32)},
                {"gray", new ColorValue(TokenValue.Empty, 128, 128, 128)},
                {"green", new ColorValue(TokenValue.Empty, 0, 128, 0)},
                {"greenyellow", new ColorValue(TokenValue.Empty, 173, 255, 47)},
                {"grey", new ColorValue(TokenValue.Empty, 128, 128, 128)},
                {"honeydew", new ColorValue(TokenValue.Empty, 240, 255, 240)},
                {"hotpink", new ColorValue(TokenValue.Empty, 255, 105, 180)},
                {"indianred", new ColorValue(TokenValue.Empty, 205, 92, 92)},
                {"indigo", new ColorValue(TokenValue.Empty, 75, 0, 130)},
                {"ivory", new ColorValue(TokenValue.Empty, 255, 255, 240)},
                {"khaki", new ColorValue(TokenValue.Empty, 240, 230, 140)},
                {"lavender", new ColorValue(TokenValue.Empty, 230, 230, 250)},
                {"lavenderblush", new ColorValue(TokenValue.Empty, 255, 240, 245)},
                {"lawngreen", new ColorValue(TokenValue.Empty, 124, 252, 0)},
                {"lemonchiffon", new ColorValue(TokenValue.Empty, 255, 250, 205)},
                {"lightblue", new ColorValue(TokenValue.Empty, 173, 216, 230)},
                {"lightcoral", new ColorValue(TokenValue.Empty, 240, 128, 128)},
                {"lightcyan", new ColorValue(TokenValue.Empty, 224, 255, 255)},
                {"lightgoldenrodyellow", new ColorValue(TokenValue.Empty, 250, 250, 210)},
                {"lightgray", new ColorValue(TokenValue.Empty, 211, 211, 211)},
                {"lightgreen", new ColorValue(TokenValue.Empty, 144, 238, 144)},
                {"lightgrey", new ColorValue(TokenValue.Empty, 211, 211, 211)},
                {"lightpink", new ColorValue(TokenValue.Empty, 255, 182, 193)},
                {"lightsalmon", new ColorValue(TokenValue.Empty, 255, 160, 122)},
                {"lightseagreen", new ColorValue(TokenValue.Empty, 32, 178, 170)},
                {"lightskyblue", new ColorValue(TokenValue.Empty, 135, 206, 250)},
                {"lightslategray", new ColorValue(TokenValue.Empty, 119, 136, 153)},
                {"lightslategrey", new ColorValue(TokenValue.Empty, 119, 136, 153)},
                {"lightsteelblue", new ColorValue(TokenValue.Empty, 176, 196, 222)},
                {"lightyellow", new ColorValue(TokenValue.Empty, 255, 255, 224)},
                {"lime", new ColorValue(TokenValue.Empty, 0, 255, 0)},
                {"limegreen", new ColorValue(TokenValue.Empty, 50, 205, 50)},
                {"linen", new ColorValue(TokenValue.Empty, 250, 240, 230)},
                {"magenta", new ColorValue(TokenValue.Empty, 255, 0, 255)},
                {"maroon", new ColorValue(TokenValue.Empty, 128, 0, 0)},
                {"mediumaquamarine", new ColorValue(TokenValue.Empty, 102, 205, 170)},
                {"mediumblue", new ColorValue(TokenValue.Empty, 0, 0, 205)},
                {"mediumorchid", new ColorValue(TokenValue.Empty, 186, 85, 211)},
                {"mediumpurple", new ColorValue(TokenValue.Empty, 147, 112, 219)},
                {"mediumseagreen", new ColorValue(TokenValue.Empty, 60, 179, 113)},
                {"mediumslateblue", new ColorValue(TokenValue.Empty, 123, 104, 238)},
                {"mediumspringgreen", new ColorValue(TokenValue.Empty, 0, 250, 154)},
                {"mediumturquoise", new ColorValue(TokenValue.Empty, 72, 209, 204)},
                {"mediumvioletred", new ColorValue(TokenValue.Empty, 199, 21, 133)},
                {"midnightblue", new ColorValue(TokenValue.Empty, 25, 25, 112)},
                {"mintcream", new ColorValue(TokenValue.Empty, 245, 255, 250)},
                {"mistyrose", new ColorValue(TokenValue.Empty, 255, 228, 225)},
                {"moccasin", new ColorValue(TokenValue.Empty, 255, 228, 181)},
                {"navajowhite", new ColorValue(TokenValue.Empty, 255, 222, 173)},
                {"navy", new ColorValue(TokenValue.Empty, 0, 0, 128)},
                {"oldlace", new ColorValue(TokenValue.Empty, 253, 245, 230)},
                {"olive", new ColorValue(TokenValue.Empty, 128, 128, 0)},
                {"olivedrab", new ColorValue(TokenValue.Empty, 107, 142, 35)},
                {"orange", new ColorValue(TokenValue.Empty, 255, 165, 0)},
                {"orangered", new ColorValue(TokenValue.Empty, 255, 69, 0)},
                {"orchid", new ColorValue(TokenValue.Empty, 218, 112, 214)},
                {"palegoldenrod", new ColorValue(TokenValue.Empty, 238, 232, 170)},
                {"palegreen", new ColorValue(TokenValue.Empty, 152, 251, 152)},
                {"paleturquoise", new ColorValue(TokenValue.Empty, 175, 238, 238)},
                {"palevioletred", new ColorValue(TokenValue.Empty, 219, 112, 147)},
                {"papayawhip", new ColorValue(TokenValue.Empty, 255, 239, 213)},
                {"peachpuff", new ColorValue(TokenValue.Empty, 255, 218, 185)},
                {"peru", new ColorValue(TokenValue.Empty, 205, 133, 63)},
                {"pink", new ColorValue(TokenValue.Empty, 255, 192, 203)},
                {"plum", new ColorValue(TokenValue.Empty, 221, 160, 221)},
                {"powderblue", new ColorValue(TokenValue.Empty, 176, 224, 230)},
                {"purple", new ColorValue(TokenValue.Empty, 128, 0, 128)},
                {"rebeccapurple", new ColorValue(TokenValue.Empty, 102, 51, 153)},
                {"red", new ColorValue(TokenValue.Empty, 255, 0, 0)},
                {"rosybrown", new ColorValue(TokenValue.Empty, 188, 143, 143)},
                {"royalblue", new ColorValue(TokenValue.Empty, 65, 105, 225)},
                {"saddlebrown", new ColorValue(TokenValue.Empty, 139, 69, 19)},
                {"salmon", new ColorValue(TokenValue.Empty, 250, 128, 114)},
                {"sandybrown", new ColorValue(TokenValue.Empty, 244, 164, 96)},
                {"seagreen", new ColorValue(TokenValue.Empty, 46, 139, 87)},
                {"seashell", new ColorValue(TokenValue.Empty, 255, 245, 238)},
                {"sienna", new ColorValue(TokenValue.Empty, 160, 82, 45)},
                {"silver", new ColorValue(TokenValue.Empty, 192, 192, 192)},
                {"skyblue", new ColorValue(TokenValue.Empty, 135, 206, 235)},
                {"slateblue", new ColorValue(TokenValue.Empty, 106, 90, 205)},
                {"slategray", new ColorValue(TokenValue.Empty, 112, 128, 144)},
                {"slategrey", new ColorValue(TokenValue.Empty, 112, 128, 144)},
                {"snow", new ColorValue(TokenValue.Empty, 255, 250, 250)},
                {"springgreen", new ColorValue(TokenValue.Empty, 0, 255, 127)},
                {"steelblue", new ColorValue(TokenValue.Empty, 70, 130, 180)},
                {"tan", new ColorValue(TokenValue.Empty, 210, 180, 140)},
                {"teal", new ColorValue(TokenValue.Empty, 0, 128, 128)},
                {"thistle", new ColorValue(TokenValue.Empty, 216, 191, 216)},
                {"tomato", new ColorValue(TokenValue.Empty, 255, 99, 71)},
                {"turquoise", new ColorValue(TokenValue.Empty, 64, 224, 208)},
                {"violet", new ColorValue(TokenValue.Empty, 238, 130, 238)},
                {"wheat", new ColorValue(TokenValue.Empty, 245, 222, 179)},
                {"white", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"whitesmoke", new ColorValue(TokenValue.Empty, 245, 245, 245)},
                {"yellow", new ColorValue(TokenValue.Empty, 255, 255, 0)},
                {"yellowgreen", new ColorValue(TokenValue.Empty, 154, 205, 50)},
                {"transparent", new ColorValue(TokenValue.Empty, 0, 0, 0, 0)},
                {"activeborder", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"activecaption", new ColorValue(TokenValue.Empty, 204, 204, 204)},
                {"appworkspace", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"background", new ColorValue(TokenValue.Empty, 99, 99, 206)},
                {"buttonface", new ColorValue(TokenValue.Empty, 221, 221, 221)},
                {"buttonhighlight", new ColorValue(TokenValue.Empty, 221, 221, 221)},
                {"buttonshadow", new ColorValue(TokenValue.Empty, 136, 136, 136)},
                {"buttontext", new ColorValue(TokenValue.Empty, 0, 0, 0)},
                {"captiontext", new ColorValue(TokenValue.Empty, 0, 0, 0)},
                {"graytext", new ColorValue(TokenValue.Empty, 128, 128, 128)},
                {"highlight", new ColorValue(TokenValue.Empty, 181, 213, 255)},
                {"highlighttext", new ColorValue(TokenValue.Empty, 0, 0, 0)},
                {"inactiveborder", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"inactivecaption", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"inactivecaptiontext", new ColorValue(TokenValue.Empty, 127, 127, 127)},
                {"infobackground", new ColorValue(TokenValue.Empty, 251, 252, 197)},
                {"infotext", new ColorValue(TokenValue.Empty, 0, 0, 0)},
                {"menu", new ColorValue(TokenValue.Empty, 247, 247, 247)},
                {"menutext", new ColorValue(TokenValue.Empty, 0, 0, 0)},
                {"scrollbar", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"threeddarkshadow", new ColorValue(TokenValue.Empty, 102, 102, 102)},
                {"threedface", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"threedhighlight", new ColorValue(TokenValue.Empty, 221, 221, 221)},
                {"threedlightshadow", new ColorValue(TokenValue.Empty, 192, 192, 192)},
                {"threedshadow", new ColorValue(TokenValue.Empty, 136, 136, 136)},
                {"window", new ColorValue(TokenValue.Empty, 255, 255, 255)},
                {"windowframe", new ColorValue(TokenValue.Empty, 204, 204, 204)},
                {"windowtext", new ColorValue(TokenValue.Empty, 0, 0, 0)}
            };

        public static IEnumerable<string> Names => NamedColors.Keys;

        public static ColorValue GetColor(string name)
        {
            if (NamedColors.TryGetValue(name, out var ColorValue)) 
                return ColorValue;

            return null;
        }

        public static string GetName(ColorValue ColorValue)
        {
            return (from pair in NamedColors where pair.Value.Equals(ColorValue) select pair.Key).FirstOrDefault();
        }
    }
}